'use client';

import { useCallback, useEffect, useRef, useState, lazy, Suspense, type FormEvent } from 'react';
import { ArrowDown, ArrowUpRight, ArrowRight, Menu, X, Plus, Move, ShieldCheck, Camera, Mail, Phone, Check, Layers3, Compass, Ruler, HardHat, Droplets, Zap, MoveUpRight } from 'lucide-react';
import HouseScene from './house-scene';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose } from '@/components/ui/sheet';
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
const Panorama=lazy(()=>import('./panorama'));

const chapters=[
 {name:'O primeiro traço',label:'01 — CONCEPÇÃO',title:<>Tudo começa<br/>com <em>uma ideia.</em></>,description:'Antes de levantar paredes, enxergamos possibilidades. Cada linha aproxima o projeto da vida que você imagina.',detail:'PROJETO ARQUITETÔNICO · COMPATIBILIZAÇÃO'},
 {name:'A estrutura',label:'02 — CONSTRUÇÃO',title:<>Confiança em<br/><em>cada detalhe.</em></>,description:'Do alicerce à cobertura, planejamento e execução caminham juntos. É aqui que o desenho começa a se tornar realidade.',detail:'ESTRUTURA · EXECUÇÃO · GERENCIAMENTO'},
 {name:'A transformação',label:'03 — ACABAMENTOS',title:<>O cuidado que<br/><em>faz a diferença.</em></>,description:'Luz, materiais e proporções em equilíbrio. A engenharia dá lugar à sensação de estar em casa.',detail:'MATERIALIDADE · CONFORTO · PRECISÃO'},
 {name:'A vida acontece',label:'04 — SEU NOVO ESPAÇO',title:<>Pode entrar.<br/><em>O futuro é seu.</em></>,description:'Mais do que uma construção pronta. Um novo cenário para a sua história, entregue com a chave na mão.',detail:'CONSTRUÇÃO COMPLETA · TURN KEY'},
];
const services=[
 {icon:Compass,title:'Projetos arquitetônicos',desc:'Estudos, aprovação municipal, topografia e desdobro de plantas. Um projeto alinhado ao seu terreno e aos seus planos.',tags:'CONCEPÇÃO / APROVAÇÃO'},
 {icon:HardHat,title:'Construção completa',desc:'Execução no modelo turn key: acompanhamento da obra até a entrega das chaves, com mão de obra especializada.',tags:'EXECUÇÃO / ENTREGA'},
 {icon:Layers3,title:'Gerenciamento de obras',desc:'Coordenação das etapas, levantamento de materiais e acompanhamento dos projetos para organizar a construção do início ao fim.',tags:'PLANEJAMENTO / CONTROLE'},
 {icon:Droplets,title:'Projetos hidráulicos',desc:'Soluções hidráulicas para imóveis residenciais, comerciais e industriais, integradas às demais disciplinas do projeto.',tags:'RESIDENCIAL / COMERCIAL / INDUSTRIAL'},
 {icon:Zap,title:'Projetos elétricos',desc:'Planejamento das instalações e visualização em 3D para antecipar decisões e integrar os sistemas ao imóvel.',tags:'INSTALAÇÕES / COMPATIBILIZAÇÃO'},
 {icon:ShieldCheck,title:'Segurança do trabalho',desc:'Vistorias, laudos e programas de segurança ocupacional. Conheça a atuação em PGR, LTCAT, LIP e NR-12.',tags:'PREVENÇÃO / CUIDADO'},
];
const safety=[['PGR','Programa de Gerenciamento de Riscos','Identificação e avaliação de riscos ocupacionais, com planejamento de medidas preventivas e acompanhamento.'],['LTCAT','Laudo Técnico das Condições Ambientais do Trabalho','Avaliação técnica das condições ambientais e da exposição dos trabalhadores a agentes nocivos.'],['LIP','Laudos de insalubridade e periculosidade','Análise das atividades e condições de exposição no ambiente de trabalho.'],['NR-12','Segurança em máquinas e equipamentos','Apoio técnico na avaliação de máquinas, equipamentos e medidas de proteção.']];
const WA='https://wa.me/5517992092338';
function Brand(){return <a className="brand" href="#inicio" aria-label="Carnegie Engenharia, início"><img src="/images/logo-original.png" width="709" height="211" alt="Carnegie Engenharia e Projetos"/></a>;}

export default function Home(){
 const journey=useRef<HTMLElement>(null),sticky=useRef<HTMLDivElement>(null),progressBar=useRef<HTMLDivElement>(null);
 const [stage,setStage]=useState(0),[started,setStarted]=useState(false),[reduced,setReduced]=useState(false),[menuOpen,setMenuOpen]=useState(false),[contactReady,setContactReady]=useState('');
 const currentStage=useRef(0),startedRef=useRef(false);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');setReduced(media.matches);const listener=()=>setReduced(media.matches);media.addEventListener('change',listener);return()=>media.removeEventListener('change',listener);},[]);
 useEffect(()=>{window.dispatchEvent(new Event('carnegie-motion-change'));},[reduced]);
 const onProgress=useCallback((p:number)=>{
  const next=p<.23?0:p<.48?1:p<.75?2:3;
  if(next!==currentStage.current){currentStage.current=next;setStage(next);}
  const hasStarted=p>.055;if(hasStarted!==startedRef.current){startedRef.current=hasStarted;setStarted(hasStarted);}
  if(progressBar.current)progressBar.current.style.transform=`scaleX(${p})`;
 },[]);
 const goToChapter=(index:number)=>{const section=journey.current;if(!section)return;const fraction=[.12,.34,.6,.96][index];window.scrollTo({top:section.offsetTop+(section.offsetHeight-(sticky.current?.offsetHeight||window.innerHeight))*fraction,behavior:reduced?'instant':'smooth'});};
 const prepareContact=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const text=`Olá, Carnegie! Quero conversar sobre um projeto.\n\nNome: ${String(data.get('nome')).trim()}\nE-mail: ${String(data.get('email')).trim()}\nTelefone: ${String(data.get('telefone')).trim()}\n\n${String(data.get('mensagem')).trim()}`;setContactReady(`${WA}?text=${encodeURIComponent(text)}`);};
 return <>
  <a className="skip-link" href="#sobre">Pular experiência e ir ao conteúdo</a>
  <header className="site-header"><Brand/><nav aria-label="Navegação principal"><a href="#sobre">A Carnegie</a><a href="#servicos">O que fazemos</a><a href="#projetos">Projetos 360°</a><a href="#contato" className="header-contact">Vamos construir <ArrowUpRight size={16}/></a></nav><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger className="mobile-menu" aria-label="Abrir menu"><Menu size={24}/></SheetTrigger><SheetContent className="mobile-sheet" showCloseButton={false}><SheetTitle>Explore a Carnegie</SheetTitle><SheetDescription>Do primeiro traço à chave na mão.</SheetDescription><SheetClose className="sheet-close" aria-label="Fechar menu"><X/></SheetClose><div className="mobile-links">{[['A Carnegie','sobre'],['O que fazemos','servicos'],['Projetos 360°','projetos'],['Segurança do trabalho','seguranca'],['Conteúdo','conteudo'],['Vamos construir','contato']].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{label}<ArrowUpRight size={20}/></a>)}</div></SheetContent></Sheet></header>
  <main>
   <section id="inicio" className={`journey ${reduced?'reduced-journey':''}`} ref={journey} aria-label="Da planta à vida: uma construção em quatro capítulos">
    <div className="journey-sticky" data-stage={stage} data-started={started} ref={sticky}>
     <div className="scene-wrap"><HouseScene journeyRef={journey} onProgress={onProgress} reducedMotion={reduced}/></div>
     <div className="scene-shade"/>
     <div className={`hero-copy ${started?'is-hidden':''}`} aria-hidden={started}><p className="eyebrow"><span/> ENGENHARIA QUE TRANSFORMA</p><h1>O seu sonho.<br/>Nossa engenharia.<br/><em>Uma nova realidade.</em></h1><p className="hero-description">Toda grande construção começa com uma ideia. Veja a sua ganhar forma, do primeiro traço à chave na mão.</p><button className="button primary" onClick={()=>goToChapter(0)} tabIndex={started?-1:0}>Explore a construção <ArrowDown size={17}/></button><div className="hero-trust"><span className="trust-line"/>PROJETAR. CONSTRUIR. TRANSFORMAR.</div></div>
     <div className={`chapter-copy ${started?'':'is-hidden'}`} aria-hidden={!started} key={stage}><p className="eyebrow"><span/>{chapters[stage].label}</p><h2>{chapters[stage].title}</h2><p className="hero-description">{chapters[stage].description}</p><p className="chapter-detail">{chapters[stage].detail}</p>{stage===3&&<a href="#contato" className="button primary" tabIndex={started?0:-1}>Vamos construir o seu? <ArrowUpRight size={17}/></a>}</div>
     <div className="scene-coordinate"><span className="live-dot"/> ESTUDO RESIDENCIAL <span>{String(stage+1).padStart(2,'0')} / 04</span></div>
     <div className="scene-annotation" aria-hidden="true">{stage===0?'IDEIA → POSSIBILIDADE':stage===1?'PRECISÃO EM CADA ETAPA':stage===2?'ESPAÇOS FEITOS PARA VIVER':'BEM-VINDO AO SEU NOVO CAPÍTULO'}</div>
     <div className="journey-bottom"><div className="journey-progress" ref={progressBar}/><span className="scroll-cue"><ArrowDown size={15}/> <span>{stage===3?'CONTINUE PARA CONHECER A CARNEGIE':'ROLE PARA DAR VIDA AO PROJETO'}</span></span><div className="chapter-nav" aria-label="Capítulos da construção">{chapters.map((chapter,i)=><button key={chapter.name} onClick={()=>goToChapter(i)} aria-label={`Ver capítulo ${i+1}: ${chapter.name}`} aria-current={stage===i?'step':undefined}><span className="chapter-dot"/><span>{chapter.name}</span></button>)}</div><span className="chapter-counter">0{stage+1} <span>/ 04</span></span></div>
     <div className="journey-options"><span>MAQUETE CONCEITUAL</span><a href="#sobre">Pular experiência <ArrowDown size={12}/></a><label htmlFor="motion">Menos movimento <Switch id="motion" checked={reduced} onCheckedChange={setReduced} size="sm"/></label></div>
    </div>
   </section>
   <div className="expertise-strip"><span>DA PLANTA À VIDA.</span><span>PROJETOS <Plus/> CONSTRUÇÃO <Plus/> GERENCIAMENTO <Plus/> SEGURANÇA</span><MoveUpRight size={24}/></div>
   <section className="section about-section" id="sobre"><div className="section-kicker"><span>01 / A CARNEGIE</span><span>ENGENHARIA COM PROPÓSITO</span></div><div className="about-grid"><div><h2>Precisão para construir.<br/><span>Visão para ir além.</span></h2><div className="experience-stat"><strong>20<span>+</span></strong><p>anos de experiência<br/>do profissional fundador</p></div></div><div className="about-copy"><p className="lead">Há um mundo de possibilidades entre uma ideia e a entrega das chaves.</p><p>A Carnegie Engenharia e Projetos conecta projetos civis, estruturas e instalações à execução e ao gerenciamento de obras.</p><p>Da consultoria em sistemas produtivos e layout às maquetes de urbanismo, reunimos conhecimento técnico e novas tecnologias em cada desafio.</p><a className="text-link" href="#servicos">Conheça nossas soluções <ArrowDown size={17}/></a></div></div><div className="about-image"><img src="/images/carnegie-project.png" alt="Imagem institucional utilizada pela Carnegie: profissionais em uma construção" loading="lazy" width="1536" height="1024"/><div className="image-statement"><span>CADA PROJETO, UM COMPROMISSO.</span><p>Construir bem.<br/>Do começo ao fim.</p></div><span className="image-caption">IMAGEM INSTITUCIONAL · ACERVO CARNEGIE</span></div></section>
   <section className="section services-section" id="servicos"><div className="section-kicker"><span>02 / O QUE FAZEMOS</span><Ruler size={18}/></div><div className="section-heading"><h2>Um parceiro.<br/><span>Todas as etapas.</span></h2><p>Seu projeto pede decisões conectadas.<br/>Nossa atuação acompanha cada uma delas.</p></div><div className="services-grid">{services.map(({icon:Icon,title,desc,tags},i)=><article className="service-card" key={title}><div className="service-top"><Icon size={27} strokeWidth={1.25}/><span>0{i+1}</span></div><h3>{title}</h3><p>{desc}</p><div className="service-bottom"><span>{tags}</span><a href={i===5?'#seguranca':'#contato'} aria-label={`Saiba mais sobre ${title}`}><ArrowUpRight size={21}/></a></div></article>)}</div><p className="service-note"><Plus size={16}/> Projetos estruturais, maquetes 3D e estudos de urbanismo também fazem parte da nossa atuação.</p></section>
   <section className="section projects-section" id="projetos"><div className="section-kicker"><span>03 / OUTROS PONTOS DE VISTA</span><span>ACERVO CARNEGIE</span></div><div className="section-heading"><h2>Enxergue além<br/><span>da planta.</span></h2><p>Explore os ambientes em 360° e descubra como a visualização aproxima o projeto da realidade.</p></div><div className="tour-grid">{[{src:'/images/tour-exterior.jpg',title:'Uma nova perspectiva',label:'VISTA EXTERNA',number:'01'},{src:'/images/tour-interior.jpg',title:'O espaço por inteiro',label:'ÁREA DE CONVIVÊNCIA',number:'02'}].map(item=><Dialog key={item.src}><DialogTrigger className="tour-card"><img src={item.src} alt={`Panorama do acervo Carnegie: ${item.label.toLowerCase()}`} loading="lazy" width="2048" height="1024"/><span className="tour-badge"><Move size={16}/> EXPLORAR 360°</span><div className="tour-info"><div><span>{item.number} / {item.label}</span><h3>{item.title}</h3></div><span className="circle-arrow"><ArrowUpRight size={25}/></span></div></DialogTrigger><DialogContent className="tour-dialog" showCloseButton={false}><div className="tour-dialog-heading"><div><DialogTitle>{item.title}</DialogTitle><DialogDescription>Arraste para olhar ao redor. Use as setas do teclado para navegar.</DialogDescription></div><DialogClose aria-label="Fechar visualização 360 graus" className="tour-close"><X/></DialogClose></div><Suspense fallback={<div className="panorama-loading">Abrindo o ambiente…</div>}><Panorama src={item.src}/></Suspense></DialogContent></Dialog>)}</div><div className="visualization-note"><Layers3 size={28} strokeWidth={1}/><p><strong>Antecipe o que ainda vai existir.</strong> Maquetes 3D ajudam a estudar possibilidades, apresentar empreendimentos e alinhar as decisões antes da execução.</p></div></section>
   <section className="section safety-section" id="seguranca"><div className="safety-intro"><p className="eyebrow">04 / SEGURANÇA DO TRABALHO</p><ShieldCheck size={44} strokeWidth={1}/><h2>O cuidado também<br/><span>é estrutural.</span></h2><p>Construir envolve pessoas. A prevenção acompanha o planejamento, a execução e a rotina de trabalho.</p><a className="text-link" href="#contato">Fale sobre segurança com a Carnegie <ArrowUpRight size={18}/></a></div><Accordion className="safety-accordion" defaultValue={['PGR']}>{safety.map(([code,title,desc])=><AccordionItem key={code} value={code}><AccordionTrigger className="safety-trigger"><div><span>{code}</span><h3>{title}</h3></div></AccordionTrigger><AccordionContent className="safety-content"><p>{desc}</p></AccordionContent></AccordionItem>)}</Accordion></section>
   <section className="section journal-section" id="conteudo"><div className="section-kicker"><span>05 / CONHECIMENTO QUE CONSTRÓI</span><a href="https://carnegieengenharia.com.br/porque-construir-em-eps/" target="_blank" rel="noopener noreferrer">BLOG CARNEGIE <ArrowUpRight size={15}/></a></div><a className="journal-article" href="https://carnegieengenharia.com.br/porque-construir-em-eps/" target="_blank" rel="noopener noreferrer"><div className="journal-image"><img src="/images/construcao-eps.png" alt="Construção em EPS, imagem do artigo da Carnegie" loading="lazy" width="900" height="600"/></div><div><span className="eyebrow">MATERIAIS & INOVAÇÃO</span><h2>Por que construir<br/>em EPS?</h2><p>Uma leitura sobre as possibilidades desse material na construção civil.</p><span className="text-link">Ler artigo no blog <ArrowUpRight size={18}/></span></div><span className="journal-arrow"><ArrowUpRight strokeWidth={1} size={70}/></span></a><div className="instagram-line"><Camera size={23}/><div><p>Acompanhe a Carnegie de perto.</p><span>Projetos, ideias e novidades no Instagram.</span></div><a href="https://www.instagram.com/carnegieengenhariaeprojetos/" target="_blank" rel="noopener noreferrer">@carnegieengenhariaeprojetos <ArrowUpRight size={17}/></a></div></section>
   <section className="section contact-section" id="contato"><div className="contact-grid"><div><p className="eyebrow">VAMOS CONSTRUIR JUNTOS</p><h2>Seu próximo<br/>capítulo<br/><span>começa aqui.</span></h2><p className="contact-intro">Uma casa, um negócio, uma nova possibilidade.<br/>Conte o que você imagina.</p><a className="contact-direct" href={WA} target="_blank" rel="noopener noreferrer"><Phone size={19}/><span>(17) 99209-2338</span><ArrowUpRight size={20}/></a><a className="contact-email" href="mailto:contato@carnegieengenharia.com.br"><Mail size={18}/> contato@carnegieengenharia.com.br</a></div><form className="contact-form" onSubmit={prepareContact} onChange={()=>setContactReady('')}><h3>Vamos conversar sobre o seu projeto.</h3><div className="form-row"><label>Seu nome<Input name="nome" autoComplete="name" placeholder="Como podemos chamar você?" required maxLength={120}/></label><label>Telefone<Input name="telefone" type="tel" autoComplete="tel" placeholder="(DDD) Seu número" required maxLength={25}/></label></div><label>E-mail<Input name="email" type="email" autoComplete="email" placeholder="voce@email.com" required maxLength={150}/></label><label>O que você tem em mente?<Textarea name="mensagem" placeholder="Conte um pouco sobre o terreno, a obra ou o projeto que você quer realizar…" required minLength={10} maxLength={2000} rows={4}/></label><button className="button contact-submit" type="submit">Preparar mensagem <ArrowRight size={19}/></button><p className="form-note">Seus dados serão usados apenas para montar a mensagem. Você revisa e envia pelo WhatsApp.</p>{contactReady&&<div className="contact-success" role="status"><Check size={20}/><div><strong>Sua mensagem está pronta.</strong><a href={contactReady} target="_blank" rel="noopener noreferrer">Abrir no WhatsApp e revisar <ArrowUpRight size={16}/></a></div></div>}</form></div></section>
  </main>
  <footer className="site-footer"><div className="footer-top"><Brand/><a href="#inicio">De volta ao primeiro traço <ArrowUpRight size={18}/></a></div><div className="footer-bottom"><p>© {new Date().getFullYear()} Carnegie Engenharia e Projetos.</p><span>CONSTRUINDO NOVAS REALIDADES.</span><div><a href="https://www.instagram.com/carnegieengenhariaeprojetos/" target="_blank" rel="noopener noreferrer">Instagram</a><a href="https://www.facebook.com/CarnegieengenhariaOficial" target="_blank" rel="noopener noreferrer">Facebook</a><a href={WA} target="_blank" rel="noopener noreferrer">WhatsApp</a></div></div></footer>
 </>;
}

